#!/usr/bin/env python3
"""
Defines an asynchronous comprehension coroutine.
"""

from typing import List
Vector = List[float]

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> Vector:
    """
    Collects 10 random numbers using asynchronous comprehension.

    This coroutine collects 10 random float numbers generated by
    the async_generator coroutine.

    Returns:
        Vector: A list of 10 random float numbers.
    """
    return [y async for y in async_generator()]
